export const data = [{
  "name":"submarine","displayName":"Submarine part request","authorName":"Poly by Google","description":"#underwater #marine #submersible #uboat\n","createTime":"2017-10-23T01:18:01.402647Z","updateTime":"2018-10-18T09:46:32.509613Z","formats":[{"root":{"relativePath":"submarine.obj","url":"https://poly.googleapis.com/downloads/dfSQmeuuYt3/1hmqYdcdQRj/submarine.obj","contentType":"text/plain"},"resources":[{"relativePath":"submarine.mtl","url":"https://poly.googleapis.com/downloads/dfSQmeuuYt3/1hmqYdcdQRj/submarine.mtl","contentType":"text/plain"}],"formatComplexity":{"triangleCount":"1348"},"formatType":"OBJ"},{"root":{"relativePath":"submarine.gltf","url":"https://poly.googleapis.com/downloads/dfSQmeuuYt3/0Dr4xEFRy1I/submarine.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"submarine.bin","url":"https://poly.googleapis.com/downloads/dfSQmeuuYt3/0Dr4xEFRy1I/submarine.bin","contentType":"application/octet-stream"}],"formatComplexity":{"triangleCount":"1348"},"formatType":"GLTF2"}],"thumbnail":{"relativePath":"dfSQmeuuYt3.png","url":"https://lh3.googleusercontent.com/-mvEtBP44H_t9AC8vf1TT7aQqs-certjSTk3gRMOf-8k55dHF1xMEVsD5oD27wEMHw","contentType":"image/png"},"license":"CREATIVE_COMMONS_BY","visibility":"PUBLIC","isCurated":true,"presentationParams":{"orientingRotation":{"w":1},"colorSpace":"LINEAR","backgroundColor":"#ffc107"}
},
{
  "name":"map","displayName":"Map view","authorName":"Robert Mirabelle","description":"Simple terrain map created in 3ds Max for use in an upcoming Tilt Brush project","createTime":"2017-11-16T02:32:50.585925Z","updateTime":"2018-10-18T09:37:07.162117Z","formats":[{"root":{"relativePath":"earth_terrain.obj","url":"https://poly.googleapis.com/downloads/2SkKFl4GjIr/0RLLmJXXGY5/earth_terrain.obj","contentType":"text/plain"},"resources":[{"relativePath":"earth_terrain.mtl","url":"https://poly.googleapis.com/downloads/2SkKFl4GjIr/0RLLmJXXGY5/earth_terrain.mtl","contentType":"text/plain"}],"formatComplexity":{"triangleCount":"194626"},"formatType":"OBJ"},{"root":{"relativePath":"earth_terrain.gltf","url":"https://poly.googleapis.com/downloads/2SkKFl4GjIr/7dO4b22ucfK/earth_terrain.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"earth_terrain.bin","url":"https://poly.googleapis.com/downloads/2SkKFl4GjIr/7dO4b22ucfK/earth_terrain.bin","contentType":"application/octet-stream"}],"formatComplexity":{"triangleCount":"194626"},"formatType":"GLTF2"}],"thumbnail":{"relativePath":"2SkKFl4GjIr.png","url":"https://lh3.googleusercontent.com/EeOlUQRbaSWAz818Dv7YoP4w8m45it7n-NRDfDC1zTLH-n7wIWgtnfjB_mQuPFCZ","contentType":"image/png"},"license":"CREATIVE_COMMONS_BY","visibility":"PUBLIC","isCurated":true,"presentationParams":{"orientingRotation":{"w":1},"colorSpace":"LINEAR","backgroundColor":"#009688"}
},
{
  "name":"dronefeed","displayName":"Drone video feed","authorName":"Billy Kwok","description":"Find out more about me, my work and my thought:\nhttps://www.billykwok.me","createTime":"2017-12-23T18:03:02.701210Z","updateTime":"2018-10-31T14:54:42.440370Z","formats":[{"root":{"relativePath":"drone.obj","url":"https://poly.googleapis.com/downloads/dDt0xsKy7qv/8zDCQeMZoLF/drone.obj","contentType":"text/plain"},"resources":[{"relativePath":"drone.mtl","url":"https://poly.googleapis.com/downloads/dDt0xsKy7qv/8zDCQeMZoLF/drone.mtl","contentType":"text/plain"}],"formatComplexity":{"triangleCount":"21287"},"formatType":"OBJ"},{"root":{"relativePath":"drone.gltf","url":"https://poly.googleapis.com/downloads/dDt0xsKy7qv/ecP212mqK1Z/drone.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"drone.bin","url":"https://poly.googleapis.com/downloads/dDt0xsKy7qv/ecP212mqK1Z/drone.bin","contentType":"application/octet-stream"}],"formatComplexity":{"triangleCount":"21287"},"formatType":"GLTF2"}],"thumbnail":{"relativePath":"thumbnail.png","url":"https://lh3.googleusercontent.com/wvMeSXJX7c5ah6lR7nLHF1vvaMFWQhczKV7qJBnelK2nytTZzCLn0-5pm4gfgB9f1Q","contentType":"image/png"},"license":"ALL_RIGHTS_RESERVED","visibility":"PUBLIC","isCurated":true,"presentationParams":{"orientingRotation":{"x":0,"y":0,"z":0,"w":0},"colorSpace":"LINEAR","backgroundColor":"#2196f3"}
},
{
  "name":"ais","displayName":"AIS data","authorName":"Thomas de Rivaz","description":"Thrown together in 15 minutes while waiting for a meeting.","createTime":"2017-07-20T15:29:51.421982Z","updateTime":"2018-10-19T09:41:09.743504Z","formats":[{"root":{"relativePath":"model.obj","url":"https://poly.googleapis.com/downloads/aYAmfkUYZjg/byf-EifNGPT/model.obj","contentType":"text/plain"},"resources":[{"relativePath":"materials.mtl","url":"https://poly.googleapis.com/downloads/aYAmfkUYZjg/byf-EifNGPT/materials.mtl","contentType":"text/plain"}],"formatComplexity":{"triangleCount":"2432"},"formatType":"OBJ"},{"root":{"relativePath":"model.gltf","url":"https://poly.googleapis.com/downloads/aYAmfkUYZjg/43SvdhTYNEI/model.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"model.bin","url":"https://poly.googleapis.com/downloads/aYAmfkUYZjg/43SvdhTYNEI/model.bin","contentType":"application/octet-stream"}],"formatComplexity":{"triangleCount":"2432"},"formatType":"GLTF"},{"root":{"relativePath":"model.gltf","url":"https://poly.googleapis.com/downloads/aYAmfkUYZjg/3SBQCE_bER-/model.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"model.bin","url":"https://poly.googleapis.com/downloads/aYAmfkUYZjg/3SBQCE_bER-/model.bin","contentType":"application/octet-stream"}],"formatComplexity":{},"formatType":"GLTF2"}],"thumbnail":{"relativePath":"aYAmfkUYZjg.png","url":"https://lh3.googleusercontent.com/Tb0WglbvloDob5jDilH1Q2Q_cCONJHBgavbkK6Q5PbUNypOaocJBiba8Xa5l-Ekt","contentType":"image/png"},"license":"CREATIVE_COMMONS_BY","visibility":"PUBLIC","isCurated":true,"presentationParams":{"orientingRotation":{"w":1},"colorSpace":"LINEAR","backgroundColor":"#3f51b5"}
},
{
  "name":"globe","displayName":"Globe","authorName":"Robert Mirabelle","description":"Built with 3ds Max.  Understanding Tilt Brush's particular support for .obj files exported from 3ds Max has been challenging, but this model showcases support for texture mapping and smoothing.","createTime":"2017-11-15T22:11:19.527866Z","updateTime":"2018-11-15T19:33:47.660701Z","formats":[{"root":{"relativePath":"earth_ball.obj","url":"https://poly.googleapis.com/downloads/0nEWYSdUqRq/6MZxN2RTSLq/earth_ball.obj","contentType":"text/plain"},"resources":[{"relativePath":"earth_ball.jpg","url":"https://poly.googleapis.com/downloads/0nEWYSdUqRq/6MZxN2RTSLq/earth_ball.jpg","contentType":"image/jpeg"},{"relativePath":"earth_ball.mtl","url":"https://poly.googleapis.com/downloads/0nEWYSdUqRq/6MZxN2RTSLq/earth_ball.mtl","contentType":"text/plain"}],"formatComplexity":{"triangleCount":"960"},"formatType":"OBJ"},{"root":{"relativePath":"earth_ball.gltf","url":"https://poly.googleapis.com/downloads/0nEWYSdUqRq/b8waCG2fqZ9/earth_ball.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"earth_ball.bin","url":"https://poly.googleapis.com/downloads/0nEWYSdUqRq/b8waCG2fqZ9/earth_ball.bin","contentType":"application/octet-stream"},{"relativePath":"earth_ball.jpg","url":"https://poly.googleapis.com/downloads/0nEWYSdUqRq/b8waCG2fqZ9/earth_ball.jpg","contentType":"image/jpeg"}],"formatComplexity":{"triangleCount":"960"},"formatType":"GLTF2"}],"thumbnail":{"relativePath":"0nEWYSdUqRq.png","url":"https://lh3.googleusercontent.com/sTlYTzSpZnMR0cHQHwcXQWUeIQkTb0-mJE9FTWf39aRG42whUzahUOqFtDiWQOKe","contentType":"image/png"},"license":"CREATIVE_COMMONS_BY","visibility":"PUBLIC","isCurated":true,"presentationParams":{"orientingRotation":{"w":1},"colorSpace":"LINEAR","backgroundColor":"#1b5e20"}
}
]





let triangle = {"name":"assets/cGwVHTq1xtc","displayName":"two triangle normal","authorName":"Anonymous","createTime":"2018-06-07T18:02:28.902540Z","updateTime":"2018-10-10T19:08:17.000609Z","formats":[{"root":{"relativePath":"two_triangle_normal.obj","url":"https://poly.googleapis.com/downloads/cGwVHTq1xtc/12jruuxFKEV/two_triangle_normal.obj","contentType":"text/plain"},"formatComplexity":{"triangleCount":"2"},"formatType":"OBJ"},{"root":{"relativePath":"two_triangle_normal.gltf","url":"https://poly.googleapis.com/downloads/cGwVHTq1xtc/18k6yH-JeNN/two_triangle_normal.gltf","contentType":"model/gltf+json"},"resources":[{"relativePath":"two_triangle_normal.bin","url":"https://poly.googleapis.com/downloads/cGwVHTq1xtc/18k6yH-JeNN/two_triangle_normal.bin","contentType":"application/octet-stream"}],"formatComplexity":{"triangleCount":"2"},"formatType":"GLTF2"}],"thumbnail":{"relativePath":"cGwVHTq1xtc.png","url":"https://lh3.googleusercontent.com/O6ibIAqOQJT5TVd-vAboGC1Acs-cOry_vial8ZWg-NztThNAD1jm8KMuGnKyDdJPRQ","contentType":"image/png"},"license":"CREATIVE_COMMONS_BY","visibility":"PUBLIC","presentationParams":{"orientingRotation":{"w":1},"colorSpace":"LINEAR","backgroundColor":"#000000"}}


export const locations = [
{ name: 'vessel', lat: 21.350, lon: -157.839, distance: '#FF3333'},
{ name: 'vessel', lat: 21.280, lon: -157.905, distance: '#FF3333'},
{ name: 'vessel', lat: 21.286, lon: -157.005, distance: 'lightgreen'},
{ name: 'vessel', lat: 21.265, lon: -157.085, distance: 'yellow'},
{ name: 'vessel', lat: 21.546, lon: -157.992, distance: '#FF3333'},
{ name: 'vessel', lat: 21.367, lon: -157.140, distance: 'lightgreen'},
{ name: 'vessel', lat: 21.287, lon: -157.585, distance: 'yellow'},
]

export const parts = [{ 
	name: 'USS Hawaii', 
	lat: 21.288712,
	lon: -157.879976,
	distance: '#FF3333',
	room: 'control room',
	partName: 'carbon dioxide scrubber',
	partImg: 'scrubber.jpg'
}
]

